### ISSUE TITLE
min_identity does not seem to work

### ISSUE THREAD

**Issue by jakobnissen** [apcamargo/pycoverm#6]
With a test BAM file, I can't actually manage to get any rows filtered away using `min_identity`.
How does it work? Also, are you sure it's a float between 0 and 1, given that its internal Rust name includes "percent"?

Can you make it work on your side?

**Comment by apcamargo** [comment]
Thanks for the report!

Despite the name, the "percent" parameters [work in the [0, 1] range](https://github.com/wwood/CoverM/blob/main/src/filter.rs#L232-L261). CoverM detects if the value is greater than 1 and then [divides it by 100](https://github.com/wwood/CoverM/blob/main/src/bin/coverm.rs#L824-L839).

I remember that in my tests the output of pyCoverM matched those of CoverM perfectly, but I didn't put together automated tests... I might be wrong, though. Unfortunately I can't investigate the issue within the next couple of days. I'll try to look into it next week.

**Comment by jakobnissen** [comment]
I was being stupid - I thought rows in the returned matrix would be removed if all reads fell below the minimum read identity. But of course this is not the behaviour (nor should it be).

Closing as solved.

**Comment by apcamargo** [comment]
No problem :)
Thanks for the update!
