### ISSUE TITLE
Ship binaries

### ISSUE THREAD

**Issue by jakobnissen** [apcamargo/pycoverm#8]
I just discovered that `pycoverm` requires Cargo to install through pip - or at least, it doesn't work when an old version of Cargo is installed.
Would it be possible to distribute precompiled binaries for major platforms?

**Comment by apcamargo** [comment]
I'm distributing binaries. Which version of Python are you using? I think I have wheels from 3.6 to 3.9

**Comment by jakobnissen** [comment]
Ah, I'm using Python 3.10. I'll just downgrade to 3.9 - but it'd be grand if binaries could be uploaded for 3.10 also :)

**Comment by jakobnissen** [comment]
It might be a good idea to restrict the Python version compat to the range for which binaries are available

**Comment by apcamargo** [comment]
Good idea. Will do that once 3.11 is available.

Just uploaded 3.10 wheels, by the way
